# Generated by Django 3.1 on 2020-10-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0003_auto_20201018_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
