# Generated by Django 3.1 on 2020-11-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0004_auto_20201018_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
