# Generated by Django 3.1 on 2020-11-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0005_auto_20201108_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
