# Generated by Django 3.1 on 2020-11-10 17:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0007_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='child_id',
        ),
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.CharField(default=datetime.datetime(2020, 11, 10, 17, 11, 31, 23528, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
