# Generated by Django 3.1 on 2020-11-14 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0010_auto_20201114_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='parents.parent'),
        ),
    ]
