# Generated by Django 3.1 on 2020-11-16 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0015_auto_20201116_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='child_id',
            new_name='childrens',
        ),
    ]
