# Generated by Django 3.1 on 2020-11-16 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0016_auto_20201116_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='childrens',
            new_name='child_id',
        ),
    ]
