# Generated by Django 3.1 on 2020-11-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0017_auto_20201116_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='child_id',
        ),
        migrations.AddField(
            model_name='child',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
