# Generated by Django 3.1 on 2020-11-16 19:30

from django.db import migrations, models
import parents.models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0018_auto_20201116_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='id',
        ),
        migrations.AddField(
            model_name='child',
            name='child_id',
            field=models.CharField(default=parents.models.generate_pk, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
